name: dart_tensor
description: A flutter package to deal with multi-dimensional list (or tensor). It include creation and manipulation of these tensors.
version: 1.0.4
homepage: https://github.com/utkarsh0702/dart_tensor

environment:
  sdk: "^3.1.0"

dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
